name: xinput_gamepad
description: Add support to XInput controllers.
version: 1.0.1
platforms:
  windows:
homepage: https://github.com/LuanRoger/xinput_gamepad
repository: https://github.com/LuanRoger/xinput_gamepad
issue_tracker: https://github.com/LuanRoger/xinput_gamepad/issues
documentation: https://github.com/LuanRoger/xinput_gamepad/wiki

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  win32: ^2.7.0
  ffi: ^2.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
