name: xinput_gamepad_package_example
description: Examples of xinput_gamepad package working.
version: 1.0.0

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  xinput_gamepad:
    path: ../..

dev_dependencies:
  lints: ^1.0.0
